import argparse
import sys
from datetime import date
from pathlib import Path

from src.catalog import ProductCatalog
from src.copy_generator import CopyGenerator
from src.discord_notifier import DiscordNotifier
from src.pinterest_client import PinterestClient
from src.pipeline import Pipeline
from src.run_log import RunLogger


def load_images(images_dir: Path, product_ids: list[str]) -> dict:
    """
    Expects files named <product_id>_<language>.jpg under images_dir.
    Images are pre-generated by a Claude Code agent via nanobanana following
    DAILY_RUN_PROMPT.md and saved into this directory ahead of time.
    """
    images = {}
    for pid in product_ids:
        for language in ("ja", "en"):
            path = Path(images_dir) / f"{pid}_{language}.jpg"
            if path.exists():
                images[(pid, language)] = path.read_bytes()
    return images


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Pinterest affiliate daily pipeline")
    parser.add_argument("--date", default=None, help="YYYY-MM-DD (default: today)")
    parser.add_argument("--images-dir", required=True)
    parser.add_argument("--catalog", default="data/catalog.json")
    parser.add_argument("--log-path", default="data/run_log.jsonl")
    parser.add_argument("--boards", required=True, help="ja_board_id:en_board_id")
    parser.add_argument("--count", type=int, default=3)
    return parser


def main(argv=None) -> int:
    args = build_arg_parser().parse_args(argv)
    target_date = date.fromisoformat(args.date) if args.date else date.today()
    ja_board, en_board = args.boards.split(":")

    catalog = ProductCatalog(args.catalog)
    products_today = catalog.pick_for_date(target_date, count=args.count)
    images = load_images(Path(args.images_dir), [p["id"] for p in products_today])

    pipeline = Pipeline(
        catalog=catalog,
        copy_generator=CopyGenerator(),
        pinterest_client=PinterestClient(),
        run_logger=RunLogger(args.log_path),
        discord=DiscordNotifier(),
        boards={"ja": ja_board, "en": en_board},
    )
    results = pipeline.run(target_date, images, count=args.count)
    for r in results:
        print(f"{r.product_id} [{r.language}]: {r.status} {r.detail}")

    return 1 if any(r.status != "posted" for r in results) else 0


if __name__ == "__main__":
    sys.exit(main())
